// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var papalOrder = PapalOrder.FromJson(jsonString);

namespace Web.Models;
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class PaypalOrder
{
  [JsonProperty("id")]
  public string Id { get; set; }

  // [JsonProperty("intent")]
  // public string Intent { get; set; }

  [JsonProperty("status")]
  public string Status { get; set; }

//   [JsonProperty("purchase_units")]
//   public PurchaseUnit[] PurchaseUnits { get; set; }

//   [JsonProperty("create_time")]
//   public DateTimeOffset CreateTime { get; set; }

//   [JsonProperty("links")]
//   public Link[] Links { get; set; }
// }

// public partial class Link
// {
//   [JsonProperty("href")]
//   public Uri Href { get; set; }

//   [JsonProperty("rel")]
//   public string Rel { get; set; }

//   [JsonProperty("method")]
//   public string Method { get; set; }
// }

// public partial class PurchaseUnit
// {
//   [JsonProperty("reference_id")]
//   public string ReferenceId { get; set; }

//   [JsonProperty("amount")]
//   public Amount Amount { get; set; }

//   [JsonProperty("payee")]
//   public Payee Payee { get; set; }
// }

// public partial class Amount
// {
//   [JsonProperty("currency_code")]
//   public string CurrencyCode { get; set; }

//   [JsonProperty("value")]
//   public string Value { get; set; }
// }

// public partial class Payee
// {
//   [JsonProperty("email_address")]
//   public string EmailAddress { get; set; }

//   [JsonProperty("merchant_id")]
//   public string MerchantId { get; set; }
// }

// public partial class PapalOrder
// {
//   public static PapalOrder FromJson(string json) => JsonConvert.DeserializeObject<PapalOrder>(json, Web.Models.Converter.Settings);
// }

// public static class Serialize
// {
//   public static string ToJson(this PapalOrder self) => JsonConvert.SerializeObject(self, Web.Models.Converter.Settings);
// }

// internal static class Converter
// {
//   public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
//   {
//     MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
//     DateParseHandling = DateParseHandling.None,
//     Converters =
//       {
//         new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
//       },
//   };
}
